apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: apidigimon-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apidigimon-pod
  template:
    metadata:
      labels:
        app: apidigimon-pod
    spec:
      containers:
      - name: apidigimon
        image: jjnavarretef/apidigimon:1.0.1
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        readinessProbe:
          httpGet:
            path: /WeatherForecast
            port: 8080
          initialDelaySeconds: 50
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /WeatherForecast
            port: 8080
          initialDelaySeconds: 50
          periodSeconds: 3