apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: apidigimon-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apidigimon
  template:
    metadata:
      labels:
        app: apidigimon
    spec:
      containers:
      - name: apidigimon
        image: jjnavarretef/apidigimon:1.0.0
        ports:
        - containerPort: 8081
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
      - name: digimondb
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          value: Jnavarrete2024*
        ports:
        - containerPort: 1434
      volumes:
      - name: digimon_db
        emptyDir: {}